name: environmentConfiguration
description: Dart package which manages the user domain.
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  dotenv: ^4.2.0
  flutter_dotenv: ^5.1.0
  # flutter_secure_storage: ^9.0.0